export interface User {
  id: string;
  email: string | null;
  created_at: string;
  is_guest: boolean;
}

export interface TokenResponse {
  access_token: string;
  token_type: string;
}

export interface ApiError {
  detail: string;
}

export interface Repo {
  id: string;
  url: string;
  name: string;
  status: "pending" | "ready" | "failed";
  created_at: string;
  // Added by the backend so a failure reason (and progress) is visible on a
  // reload/bookmark/shared link that has no `?job=` query param -- the
  // in-flight `useJobPolling` job only exists right after submission, when
  // the URL still carries that param. Optional/nullable because this field
  // may not exist yet on responses from a not-yet-updated backend deploy;
  // treat it defensively (it may be `undefined` as well as `null`).
  latest_job?: Job | null;
  // Populated by the backend once analysis completes -- may be `null`/absent
  // while a job is still running, or on a repo analyzed before this feature
  // existed. Always code the optional-chaining/fallback path.
  domain_briefing?: DomainBriefing | null;
}

// "Executive briefing" summary generated by the backend's domain
// classification pass. See `components/workspace/repo-briefing.tsx`.
export interface DomainBriefing {
  primary_field: string;
  target_audience: string;
  architecture_overview: string;
  tech_stack_badges: string[];
  file_type_distribution: { label: string; count: number }[];
  // Beginner-facing "onboarding guide" fields -- optional/nullable because
  // a response from a not-yet-updated backend deploy (or a repo analyzed
  // before this feature existed, briefly, mid-rollout) may omit them
  // entirely; may also be present but empty if the LLM omitted them (see
  // app.core.domain_briefing.generate_domain_briefing). Always code the
  // empty-state path.
  beginner_summary?: string;
  tech_stack_explained?: { name: string; role: string }[];
  learning_path?: { file_or_topic: string; why: string }[];
  key_takeaways?: string[];
}

export interface Job {
  id: string;
  repo_id: string;
  status: "pending" | "running" | "completed" | "failed";
  progress: number;
  error_message: string | null;
  skipped_files: number;
  started_at: string | null;
  finished_at: string | null;
  // Optional/nullable -- may be absent on a not-yet-updated backend deploy.
  // See `components/workspace/analysis-progress.tsx`.
  stage?: "cloning" | "parsing" | "embedding" | "completed" | null;
}

export interface AnalyzeRepoResponse {
  repo_id: string;
  job_id: string;
}

export interface FileTreeEntry {
  name: string;
  path: string;
  type: "file" | "directory";
  children: FileTreeEntry[] | null;
}

export interface FileTreeResponse {
  entries: FileTreeEntry[];
}

export interface FileContentResponse {
  path: string;
  content: string;
}

// AI-generated per-block annotations for a file, shown by the Annotated
// View toggle in CodeViewer. See
// app/api/repos/[repoId]/files/annotations/route.ts and
// components/workspace/code-viewer.tsx. `category` is a closed set that
// must match the backend contract exactly -- a mismatch here would break
// rendering on real data.
export interface CodeBlockAnnotation {
  category: "imports" | "config_state" | "business_logic" | "handlers_endpoints";
  start_line: number; // 1-indexed, inclusive
  end_line: number; // 1-indexed, inclusive
  logic_summary: string;
  flow: string;
  tips: string;
}

export interface FileAnnotationsResponse {
  path: string;
  blocks: CodeBlockAnnotation[];
}

// Flagship tools -- see app/api/routes/flagship.py. All three are lazily
// generated on the backend and cached from then on, so a GET is cheap after
// the first request for a given repo.
export interface ReadmeResponse {
  content: string;
}

export interface SecurityFinding {
  severity: "critical" | "high" | "medium" | "low";
  category: "security" | "bug" | "anti_pattern";
  file: string;
  line: number | null;
  title: string;
  description: string;
}

export interface SecurityScanResponse {
  findings: SecurityFinding[];
}

export interface HealthScoreResponse {
  overall_score: number;
  sub_scores: {
    documentation: number;
    testing: number;
    automation: number;
    quality: number;
  };
  commentary: string;
  signals: {
    has_readme: boolean;
    has_tests: boolean;
    has_ci: boolean;
    has_license: boolean;
  };
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correct_index: number;
  explanation: string;
}

export interface QuizResponse {
  questions: QuizQuestion[];
}

export interface FlowMapResponse {
  diagram: string;
}

export interface RefactorRecipe {
  file: string;
  issue: string;
  estimated_hours: number;
  before_snippet: string;
  after_snippet: string;
  explanation: string;
}

export interface TechDebtResponse {
  estimated_debt_hours: number;
  summary: string;
  items: RefactorRecipe[];
}

export interface LicenseFinding {
  package: string;
  ecosystem: string;
  likely_license: string;
  risk: "low" | "medium" | "high" | "unknown";
  note: string;
}

export interface SecretFinding {
  file: string;
  line: number;
  pattern: string;
  preview: string;
}

export interface DangerousPatternFinding {
  file: string;
  line: number;
  pattern: string;
  severity: "low" | "medium" | "high";
  rationale: string;
  snippet: string;
}

export interface ComplianceScanResponse {
  overall_risk: "low" | "medium" | "high" | "unknown";
  license_findings: LicenseFinding[];
  secret_findings: SecretFinding[];
  dangerous_pattern_findings: DangerousPatternFinding[];
  disclaimer: string;
}

export interface RouteFinding {
  method: string;
  path: string;
  file: string;
  line: number;
  framework: string;
  path_params: string[];
  auth_required: boolean;
}

export interface RouteExplorerResponse {
  routes: RouteFinding[];
  frameworks_detected: string[];
  disclaimer: string;
}

export interface ComplexityHotspot {
  file: string;
  function: string;
  line: number;
  complexity: number;
  maintainability: number;
  line_count: number;
}

export interface ComplexityRadarResponse {
  functions_analyzed: number;
  average_complexity: number;
  hotspots: ComplexityHotspot[];
  disclaimer: string;
}

export interface ModuleMapResponse {
  diagram: string;
  directory_count: number;
  file_count: number;
}

export interface BootstrapResponse {
  stacks_detected: string[];
  services_detected: string[];
  dockerfile: string;
  docker_compose: string;
  setup_script: string;
}

export interface RepoMetrics {
  file_count: number;
  lines_of_code: number;
  average_complexity: number;
  functions_analyzed: number;
  route_count: number;
  frameworks_detected: string[];
  vulnerability_count: number;
  overall_risk: "low" | "medium" | "high" | "unknown";
  module_breakdown: Record<string, number>;
}

export interface RepoCompareSide {
  repo_id: string;
  name: string;
  url: string;
  metrics: RepoMetrics;
}

export interface RepoCompareDeltas {
  file_count_delta: number;
  lines_of_code_delta: number;
  average_complexity_delta: number;
  route_count_delta: number;
  vulnerability_count_delta: number;
}

export interface RepoCompareResponse {
  repo_a: RepoCompareSide;
  repo_b: RepoCompareSide;
  deltas: RepoCompareDeltas;
  security_verdict: string;
  disclaimer: string;
}

export interface Conversation {
  id: string;
  repo_id: string;
  title: string;
  created_at: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  created_at: string;
}
