export interface User {
  id: string;
  email: string;
  created_at: string;
}

export interface TokenResponse {
  access_token: string;
  token_type: string;
}

export interface ApiError {
  detail: string;
}

export interface Repo {
  id: string;
  url: string;
  name: string;
  status: "pending" | "ready" | "failed";
  created_at: string;
  // Added by the backend so a failure reason (and progress) is visible on a
  // reload/bookmark/shared link that has no `?job=` query param -- the
  // in-flight `useJobPolling` job only exists right after submission, when
  // the URL still carries that param. Optional/nullable because this field
  // may not exist yet on responses from a not-yet-updated backend deploy;
  // treat it defensively (it may be `undefined` as well as `null`).
  latest_job?: Job | null;
  // Populated by the backend once analysis completes -- may be `null`/absent
  // while a job is still running, or on a repo analyzed before this feature
  // existed. Always code the optional-chaining/fallback path.
  domain_briefing?: DomainBriefing | null;
}

// "Executive briefing" summary generated by the backend's domain
// classification pass. See `components/workspace/repo-briefing.tsx`.
export interface DomainBriefing {
  primary_field: string;
  target_audience: string;
  architecture_overview: string;
  tech_stack_badges: string[];
  file_type_distribution: { label: string; count: number }[];
}

export interface Job {
  id: string;
  repo_id: string;
  status: "pending" | "running" | "completed" | "failed";
  progress: number;
  error_message: string | null;
  skipped_files: number;
  started_at: string | null;
  finished_at: string | null;
  // Optional/nullable -- may be absent on a not-yet-updated backend deploy.
  // See `components/workspace/analysis-progress.tsx`.
  stage?: "cloning" | "parsing" | "embedding" | "completed" | null;
}

export interface AnalyzeRepoResponse {
  repo_id: string;
  job_id: string;
}

export interface FileTreeEntry {
  name: string;
  path: string;
  type: "file" | "directory";
  children: FileTreeEntry[] | null;
}

export interface FileTreeResponse {
  entries: FileTreeEntry[];
}

export interface FileContentResponse {
  path: string;
  content: string;
}

export interface Conversation {
  id: string;
  repo_id: string;
  title: string;
  created_at: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  created_at: string;
}
